# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.attachments_attachment_gid.delete import DeleteSpecificRaw
from asana_python_sdk.paths.attachments.get import GetAllForObjectRaw
from asana_python_sdk.paths.attachments_attachment_gid.get import GetAttachmentRecordRaw
from asana_python_sdk.paths.attachments.post import UploadAttachmentRaw


class AttachmentsApiRaw(
    DeleteSpecificRaw,
    GetAllForObjectRaw,
    GetAttachmentRecordRaw,
    UploadAttachmentRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
