# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.batch.post import SubmitParallelRequests
from asana_python_sdk.apis.tags.batch_api_api_raw import BatchAPIApiRaw


class BatchAPIApi(
    SubmitParallelRequests,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BatchAPIApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BatchAPIApiRaw(api_client)
