# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.events.get import GetResourceEvents
from asana_python_sdk.apis.tags.events_api_raw import EventsApiRaw


class EventsApi(
    GetResourceEvents,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EventsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EventsApiRaw(api_client)
