# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.goals_goal_gid_add_supporting_relationship.post import CreateSupportingRelationship
from asana_python_sdk.paths.goal_relationships.get import GetCompactRecords
from asana_python_sdk.paths.goal_relationships_goal_relationship_gid.get import GetRecordById
from asana_python_sdk.paths.goals_goal_gid_remove_supporting_relationship.post import RemoveSupportingRelationship
from asana_python_sdk.paths.goal_relationships_goal_relationship_gid.put import UpdateGoalRelationshipRecord
from asana_python_sdk.apis.tags.goal_relationships_api_raw import GoalRelationshipsApiRaw


class GoalRelationshipsApi(
    CreateSupportingRelationship,
    GetCompactRecords,
    GetRecordById,
    RemoveSupportingRelationship,
    UpdateGoalRelationshipRecord,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GoalRelationshipsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GoalRelationshipsApiRaw(api_client)
