# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.goals_goal_gid_add_followers.post import AddCollaboratorsToGoal
from asana_python_sdk.paths.goals_goal_gid_set_metric.post import CreateMetric
from asana_python_sdk.paths.goals.post import CreateNewGoalRecord
from asana_python_sdk.paths.goals_goal_gid.delete import DeleteRecord
from asana_python_sdk.paths.goals.get import GetCompactRecords
from asana_python_sdk.paths.goals_goal_gid.get import GetGoalRecord
from asana_python_sdk.paths.goals_goal_gid_parent_goals.get import GetParentGoals
from asana_python_sdk.paths.goals_goal_gid_remove_followers.post import RemoveFollowersFromGoal
from asana_python_sdk.paths.goals_goal_gid.put import UpdateGoalRecord
from asana_python_sdk.paths.goals_goal_gid_set_metric_current_value.post import UpdateMetricCurrentValue
from asana_python_sdk.apis.tags.goals_api_raw import GoalsApiRaw


class GoalsApi(
    AddCollaboratorsToGoal,
    CreateMetric,
    CreateNewGoalRecord,
    DeleteRecord,
    GetCompactRecords,
    GetGoalRecord,
    GetParentGoals,
    RemoveFollowersFromGoal,
    UpdateGoalRecord,
    UpdateMetricCurrentValue,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GoalsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GoalsApiRaw(api_client)
