# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.memberships.post import CreateNewRecordRaw
from asana_python_sdk.paths.memberships_membership_gid.delete import DeleteRecordRaw
from asana_python_sdk.paths.memberships_membership_gid.get import GetMembershipRecordRaw
from asana_python_sdk.paths.memberships.get import GetMultipleRaw


class MembershipsApiRaw(
    CreateNewRecordRaw,
    DeleteRecordRaw,
    GetMembershipRecordRaw,
    GetMultipleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
