# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.portfolios_portfolio_gid_portfolio_memberships.get import GetCompactRaw
from asana_python_sdk.paths.portfolio_memberships_portfolio_membership_gid.get import GetCompleteRecordRaw
from asana_python_sdk.paths.portfolio_memberships.get import ListMultipleMembershipsRaw


class PortfolioMembershipsApiRaw(
    GetCompactRaw,
    GetCompleteRecordRaw,
    ListMultipleMembershipsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
