# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.portfolios_portfolio_gid_add_custom_field_setting.post import AddCustomFieldSetting
from asana_python_sdk.paths.portfolios_portfolio_gid_add_members.post import AddMembersToPortfolio
from asana_python_sdk.paths.portfolios_portfolio_gid_add_item.post import AddPortfolioItem
from asana_python_sdk.paths.portfolios.post import CreateNewPortfolioRecord
from asana_python_sdk.paths.portfolios_portfolio_gid.delete import DeleteRecord
from asana_python_sdk.paths.portfolios_portfolio_gid_items.get import GetItems
from asana_python_sdk.paths.portfolios_portfolio_gid.get import GetRecord
from asana_python_sdk.paths.portfolios.get import ListMultiplePortfolios
from asana_python_sdk.paths.portfolios_portfolio_gid_remove_custom_field_setting.post import RemoveCustomFieldSetting
from asana_python_sdk.paths.portfolios_portfolio_gid_remove_item.post import RemoveItemFromPortfolio
from asana_python_sdk.paths.portfolios_portfolio_gid_remove_members.post import RemoveMembersFromPortfolio
from asana_python_sdk.paths.portfolios_portfolio_gid.put import UpdatePortfolioRecord
from asana_python_sdk.apis.tags.portfolios_api_raw import PortfoliosApiRaw


class PortfoliosApi(
    AddCustomFieldSetting,
    AddMembersToPortfolio,
    AddPortfolioItem,
    CreateNewPortfolioRecord,
    DeleteRecord,
    GetItems,
    GetRecord,
    ListMultiplePortfolios,
    RemoveCustomFieldSetting,
    RemoveItemFromPortfolio,
    RemoveMembersFromPortfolio,
    UpdatePortfolioRecord,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PortfoliosApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PortfoliosApiRaw(api_client)
