# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.portfolios_portfolio_gid_add_custom_field_setting.post import AddCustomFieldSettingRaw
from asana_python_sdk.paths.portfolios_portfolio_gid_add_members.post import AddMembersToPortfolioRaw
from asana_python_sdk.paths.portfolios_portfolio_gid_add_item.post import AddPortfolioItemRaw
from asana_python_sdk.paths.portfolios.post import CreateNewPortfolioRecordRaw
from asana_python_sdk.paths.portfolios_portfolio_gid.delete import DeleteRecordRaw
from asana_python_sdk.paths.portfolios_portfolio_gid_items.get import GetItemsRaw
from asana_python_sdk.paths.portfolios_portfolio_gid.get import GetRecordRaw
from asana_python_sdk.paths.portfolios.get import ListMultiplePortfoliosRaw
from asana_python_sdk.paths.portfolios_portfolio_gid_remove_custom_field_setting.post import RemoveCustomFieldSettingRaw
from asana_python_sdk.paths.portfolios_portfolio_gid_remove_item.post import RemoveItemFromPortfolioRaw
from asana_python_sdk.paths.portfolios_portfolio_gid_remove_members.post import RemoveMembersFromPortfolioRaw
from asana_python_sdk.paths.portfolios_portfolio_gid.put import UpdatePortfolioRecordRaw


class PortfoliosApiRaw(
    AddCustomFieldSettingRaw,
    AddMembersToPortfolioRaw,
    AddPortfolioItemRaw,
    CreateNewPortfolioRecordRaw,
    DeleteRecordRaw,
    GetItemsRaw,
    GetRecordRaw,
    ListMultiplePortfoliosRaw,
    RemoveCustomFieldSettingRaw,
    RemoveItemFromPortfolioRaw,
    RemoveMembersFromPortfolioRaw,
    UpdatePortfolioRecordRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
