# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.portfolios_portfolio_gid_portfolio_memberships.get import GetCompact
from asana_python_sdk.paths.portfolio_memberships_portfolio_membership_gid.get import GetCompleteRecord
from asana_python_sdk.paths.portfolio_memberships.get import ListMultipleMemberships
from asana_python_sdk.apis.tags.portfolio_memberships_api_raw import PortfolioMembershipsApiRaw


class PortfolioMembershipsApi(
    GetCompact,
    GetCompleteRecord,
    ListMultipleMemberships,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PortfolioMembershipsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PortfolioMembershipsApiRaw(api_client)
