# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.projects_project_gid_project_statuses.post import CreateNewStatusUpdateRecordRaw
from asana_python_sdk.paths.project_statuses_project_status_gid.delete import DeleteSpecificStatusUpdateRaw
from asana_python_sdk.paths.projects_project_gid_project_statuses.get import GetProjectUpdatesRaw
from asana_python_sdk.paths.project_statuses_project_status_gid.get import GetStatusUpdateRecordRaw


class ProjectStatusesApiRaw(
    CreateNewStatusUpdateRecordRaw,
    DeleteSpecificStatusUpdateRaw,
    GetProjectUpdatesRaw,
    GetStatusUpdateRecordRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
