# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.project_templates_project_template_gid.delete import DeleteTemplateRecord
from asana_python_sdk.paths.teams_team_gid_project_templates.get import GetAllTemplateRecords
from asana_python_sdk.paths.project_templates_project_template_gid.get import GetRecord
from asana_python_sdk.paths.project_templates_project_template_gid_instantiate_project.post import InstantiateProjectJob
from asana_python_sdk.paths.project_templates.get import ListMultiple
from asana_python_sdk.apis.tags.project_templates_api_raw import ProjectTemplatesApiRaw


class ProjectTemplatesApi(
    DeleteTemplateRecord,
    GetAllTemplateRecords,
    GetRecord,
    InstantiateProjectJob,
    ListMultiple,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProjectTemplatesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProjectTemplatesApiRaw(api_client)
