# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.projects_project_gid_project_briefs.post import CreateNewRecord
from asana_python_sdk.paths.project_briefs_project_brief_gid.get import GetFullRecord
from asana_python_sdk.paths.project_briefs_project_brief_gid.delete import RemoveBrief
from asana_python_sdk.paths.project_briefs_project_brief_gid.put import UpdateBriefRecord
from asana_python_sdk.apis.tags.project_briefs_api_raw import ProjectBriefsApiRaw


class ProjectBriefsApi(
    CreateNewRecord,
    GetFullRecord,
    RemoveBrief,
    UpdateBriefRecord,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProjectBriefsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProjectBriefsApiRaw(api_client)
