# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.projects_project_gid_project_statuses.post import CreateNewStatusUpdateRecord
from asana_python_sdk.paths.project_statuses_project_status_gid.delete import DeleteSpecificStatusUpdate
from asana_python_sdk.paths.projects_project_gid_project_statuses.get import GetProjectUpdates
from asana_python_sdk.paths.project_statuses_project_status_gid.get import GetStatusUpdateRecord
from asana_python_sdk.apis.tags.project_statuses_api_raw import ProjectStatusesApiRaw


class ProjectStatusesApi(
    CreateNewStatusUpdateRecord,
    DeleteSpecificStatusUpdate,
    GetProjectUpdates,
    GetStatusUpdateRecord,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProjectStatusesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProjectStatusesApiRaw(api_client)
