# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.sections_section_gid_add_task.post import AddTaskToSectionRaw
from asana_python_sdk.paths.projects_project_gid_sections.post import CreateNewSectionRaw
from asana_python_sdk.paths.sections_section_gid.delete import DeleteSectionRaw
from asana_python_sdk.paths.sections_section_gid.get import GetRecordRaw
from asana_python_sdk.paths.projects_project_gid_sections.get import ListProjectSectionsRaw
from asana_python_sdk.paths.projects_project_gid_sections_insert.post import MoveOrInsertRaw
from asana_python_sdk.paths.sections_section_gid.put import UpdateSectionRecordRaw


class SectionsApiRaw(
    AddTaskToSectionRaw,
    CreateNewSectionRaw,
    DeleteSectionRaw,
    GetRecordRaw,
    ListProjectSectionsRaw,
    MoveOrInsertRaw,
    UpdateSectionRecordRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
