# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.tasks_task_gid_stories.post import CreateComment
from asana_python_sdk.paths.stories_story_gid.delete import DeleteStoryRecord
from asana_python_sdk.paths.stories_story_gid.get import GetFullRecord
from asana_python_sdk.paths.tasks_task_gid_stories.get import GetTaskStories
from asana_python_sdk.paths.stories_story_gid.put import UpdateFullRecord
from asana_python_sdk.apis.tags.stories_api_raw import StoriesApiRaw


class StoriesApi(
    CreateComment,
    DeleteStoryRecord,
    GetFullRecord,
    GetTaskStories,
    UpdateFullRecord,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: StoriesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = StoriesApiRaw(api_client)
