# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.tags.post import CreateNewTagRecordRaw
from asana_python_sdk.paths.workspaces_workspace_gid_tags.post import CreateTagInWorkspaceRaw
from asana_python_sdk.paths.workspaces_workspace_gid_tags.get import GetFilteredTagsRaw
from asana_python_sdk.paths.tags_tag_gid.get import GetRecordRaw
from asana_python_sdk.paths.tasks_task_gid_tags.get import GetTaskTagsRaw
from asana_python_sdk.paths.tags.get import ListFilteredTagsRaw
from asana_python_sdk.paths.tags_tag_gid.delete import RemoveTagRaw
from asana_python_sdk.paths.tags_tag_gid.put import UpdateTagRecordRaw


class TagsApiRaw(
    CreateNewTagRecordRaw,
    CreateTagInWorkspaceRaw,
    GetFilteredTagsRaw,
    GetRecordRaw,
    GetTaskTagsRaw,
    ListFilteredTagsRaw,
    RemoveTagRaw,
    UpdateTagRecordRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
