# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.tags.post import CreateNewTagRecord
from asana_python_sdk.paths.workspaces_workspace_gid_tags.post import CreateTagInWorkspace
from asana_python_sdk.paths.workspaces_workspace_gid_tags.get import GetFilteredTags
from asana_python_sdk.paths.tags_tag_gid.get import GetRecord
from asana_python_sdk.paths.tasks_task_gid_tags.get import GetTaskTags
from asana_python_sdk.paths.tags.get import ListFilteredTags
from asana_python_sdk.paths.tags_tag_gid.delete import RemoveTag
from asana_python_sdk.paths.tags_tag_gid.put import UpdateTagRecord
from asana_python_sdk.apis.tags.tags_api_raw import TagsApiRaw


class TagsApi(
    CreateNewTagRecord,
    CreateTagInWorkspace,
    GetFilteredTags,
    GetRecord,
    GetTaskTags,
    ListFilteredTags,
    RemoveTag,
    UpdateTagRecord,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TagsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TagsApiRaw(api_client)
