# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.task_templates_task_template_gid.delete import DeleteTaskTemplateRaw
from asana_python_sdk.paths.task_templates_task_template_gid.get import GetSingleTemplateRaw
from asana_python_sdk.paths.task_templates_task_template_gid_instantiate_task.post import InstantiateTaskJobRaw
from asana_python_sdk.paths.task_templates.get import ListMultipleRaw


class TaskTemplatesApiRaw(
    DeleteTaskTemplateRaw,
    GetSingleTemplateRaw,
    InstantiateTaskJobRaw,
    ListMultipleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
