# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.teams_team_gid_team_memberships.get import GetCompact
from asana_python_sdk.paths.team_memberships.get import GetCompactRecords
from asana_python_sdk.paths.team_memberships_team_membership_gid.get import GetRecordById
from asana_python_sdk.paths.users_user_gid_team_memberships.get import GetUserCompact
from asana_python_sdk.apis.tags.team_memberships_api_raw import TeamMembershipsApiRaw


class TeamMembershipsApi(
    GetCompact,
    GetCompactRecords,
    GetRecordById,
    GetUserCompact,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TeamMembershipsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TeamMembershipsApiRaw(api_client)
