# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.teams_team_gid_team_memberships.get import GetCompactRaw
from asana_python_sdk.paths.team_memberships.get import GetCompactRecordsRaw
from asana_python_sdk.paths.team_memberships_team_membership_gid.get import GetRecordByIdRaw
from asana_python_sdk.paths.users_user_gid_team_memberships.get import GetUserCompactRaw


class TeamMembershipsApiRaw(
    GetCompactRaw,
    GetCompactRecordsRaw,
    GetRecordByIdRaw,
    GetUserCompactRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
