# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.teams_team_gid_add_user.post import AddUserToTeamRaw
from asana_python_sdk.paths.teams.post import CreateTeamRecordRaw
from asana_python_sdk.paths.teams_team_gid.get import GetTeamRecordRaw
from asana_python_sdk.paths.users_user_gid_teams.get import GetUserTeamsRaw
from asana_python_sdk.paths.workspaces_workspace_gid_teams.get import ListWorkspaceTeamsRaw
from asana_python_sdk.paths.teams_team_gid_remove_user.post import RemoveUserFromTeamRaw
from asana_python_sdk.paths.teams_team_gid.put import UpdateTeamRecordRaw


class TeamsApiRaw(
    AddUserToTeamRaw,
    CreateTeamRecordRaw,
    GetTeamRecordRaw,
    GetUserTeamsRaw,
    ListWorkspaceTeamsRaw,
    RemoveUserFromTeamRaw,
    UpdateTeamRecordRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
