# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.teams_team_gid_add_user.post import AddUserToTeam
from asana_python_sdk.paths.teams.post import CreateTeamRecord
from asana_python_sdk.paths.teams_team_gid.get import GetTeamRecord
from asana_python_sdk.paths.users_user_gid_teams.get import GetUserTeams
from asana_python_sdk.paths.workspaces_workspace_gid_teams.get import ListWorkspaceTeams
from asana_python_sdk.paths.teams_team_gid_remove_user.post import RemoveUserFromTeam
from asana_python_sdk.paths.teams_team_gid.put import UpdateTeamRecord
from asana_python_sdk.apis.tags.teams_api_raw import TeamsApiRaw


class TeamsApi(
    AddUserToTeam,
    CreateTeamRecord,
    GetTeamRecord,
    GetUserTeams,
    ListWorkspaceTeams,
    RemoveUserFromTeam,
    UpdateTeamRecord,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TeamsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TeamsApiRaw(api_client)
