# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.tasks_task_gid_time_tracking_entries.post import CreateNewTimeEntryRecord
from asana_python_sdk.paths.time_tracking_entries_time_tracking_entry_gid.delete import DeleteTimeEntry
from asana_python_sdk.paths.tasks_task_gid_time_tracking_entries.get import GetForTask
from asana_python_sdk.paths.time_tracking_entries_time_tracking_entry_gid.get import GetRecord
from asana_python_sdk.paths.time_tracking_entries_time_tracking_entry_gid.put import UpdateTimeTrackingEntry
from asana_python_sdk.apis.tags.time_tracking_entries_api_raw import TimeTrackingEntriesApiRaw


class TimeTrackingEntriesApi(
    CreateNewTimeEntryRecord,
    DeleteTimeEntry,
    GetForTask,
    GetRecord,
    UpdateTimeTrackingEntry,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TimeTrackingEntriesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TimeTrackingEntriesApiRaw(api_client)
