# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.time_periods.get import GetCompactTimePeriods
from asana_python_sdk.paths.time_periods_time_period_gid.get import GetFullRecord
from asana_python_sdk.apis.tags.time_periods_api_raw import TimePeriodsApiRaw


class TimePeriodsApi(
    GetCompactTimePeriods,
    GetFullRecord,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TimePeriodsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TimePeriodsApiRaw(api_client)
