# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.tasks_task_gid_time_tracking_entries.post import CreateNewTimeEntryRecordRaw
from asana_python_sdk.paths.time_tracking_entries_time_tracking_entry_gid.delete import DeleteTimeEntryRaw
from asana_python_sdk.paths.tasks_task_gid_time_tracking_entries.get import GetForTaskRaw
from asana_python_sdk.paths.time_tracking_entries_time_tracking_entry_gid.get import GetRecordRaw
from asana_python_sdk.paths.time_tracking_entries_time_tracking_entry_gid.put import UpdateTimeTrackingEntryRaw


class TimeTrackingEntriesApiRaw(
    CreateNewTimeEntryRecordRaw,
    DeleteTimeEntryRaw,
    GetForTaskRaw,
    GetRecordRaw,
    UpdateTimeTrackingEntryRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
