# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.workspaces_workspace_gid_typeahead.get import GetResults
from asana_python_sdk.apis.tags.typeahead_api_raw import TypeaheadApiRaw


class TypeaheadApi(
    GetResults,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TypeaheadApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TypeaheadApiRaw(api_client)
