# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.user_task_lists_user_task_list_gid.get import GetRecordRaw
from asana_python_sdk.paths.users_user_gid_user_task_list.get import GetUserTaskListRaw


class UserTaskListsApiRaw(
    GetRecordRaw,
    GetUserTaskListRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
