# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec](https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.users_user_gid_favorites.get import GetFavoritesForUserRaw
from asana_python_sdk.paths.users_user_gid.get import GetUserRecordRaw
from asana_python_sdk.paths.users.get import ListMultipleUsersRaw
from asana_python_sdk.paths.teams_team_gid_users.get import ListTeamUsersRaw
from asana_python_sdk.paths.workspaces_workspace_gid_users.get import ListWorkspaceUsersRaw


class UsersApiRaw(
    GetFavoritesForUserRaw,
    GetUserRecordRaw,
    ListMultipleUsersRaw,
    ListTeamUsersRaw,
    ListWorkspaceUsersRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
