# coding: utf-8

"""
    Asana

    This is the interface for interacting with the [Asana Platform](https://developers.asana.com). Our API reference is generated from our [OpenAPI spec] (https://raw.githubusercontent.com/Asana/openapi/master/defs/asana_oas.yaml).

    The version of the OpenAPI document: 1.0
    Created by: https://asana.com/support
"""

from asana_python_sdk.paths.webhooks.post import EstablishWebhook
from asana_python_sdk.paths.webhooks_webhook_gid.get import GetWebhookRecord
from asana_python_sdk.paths.webhooks.get import ListMultipleWebhooks
from asana_python_sdk.paths.webhooks_webhook_gid.delete import RemoveWebhook
from asana_python_sdk.paths.webhooks_webhook_gid.put import UpdateWebhookFilters
from asana_python_sdk.apis.tags.webhooks_api_raw import WebhooksApiRaw


class WebhooksApi(
    EstablishWebhook,
    GetWebhookRecord,
    ListMultipleWebhooks,
    RemoveWebhook,
    UpdateWebhookFilters,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WebhooksApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WebhooksApiRaw(api_client)
